### ISSUE TITLE
Legislatures should be checked using both P194 and P1001

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/legislative-explorer#1]
Currently the query to find the legislature for a jurisdiction looks for a `P194 (legislative body)` statement, and if none is found, reports it as unknown.

However, there are two different ways this information can be found in Wikidata — the legislature itself could also have a `P1001 (applies to jurisdiction)` statement pointing back to the place.

We should try to find the legislature in both directions, and highlight cases where this information is ether inconsistent, or is only expressed in one way or the other.

**Comment by henare** [comment]
I've extracted this into three separate issues. I think this encompasses all the new things we want the application to do but if I've missed anything please reopen this or create new issues.
