### ISSUE TITLE
Can't run test files separately

### ISSUE THREAD

**Issue by henare** [everypolitician/legislative-explorer#14]
# Problem

You can't currently just run one test file. For instance when you're focussing on a particular area of the application, e.g.

```
$ bundle exec ruby -w -I"lib:t" "t/page/country.rb"
RUBY_GC_MALLOC_LIMIT=59000000 (default value: 16777216)
Run options: --seed 4534

# Running:

EEEEEEEEEE

Finished in 0.002656s, 3765.6174 runs/s, 0.0000 assertions/s.

  1) Error:
Estonia Page::title#test_0001_should give the country name in the title:
NameError: uninitialized constant Query
    /home/henare/Documents/projects/mysociety/legislative-explorer/t/page/country.rb:7:in `country_page'
    /home/henare/Documents/projects/mysociety/legislative-explorer/t/page/country.rb:15:in `block (3 levels) in <top (required)>'
    /home/henare/.rvm/gems/ruby-2.3.3/gems/vcr-4.0.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
    /home/henare/.rvm/gems/ruby-2.3.3/gems/vcr-4.0.0/lib/vcr.rb:188:in `use_cassette'
    /home/henare/Documents/projects/mysociety/legislative-explorer/t/page/country.rb:15:in `block (2 levels) in <top (required)>'
[snip]

```

In the case above it's because the test uses classes in the Query module such as Query::CountryInfo and the files defining these classes aren't `require`d.

# Proposed Solution

Strictly speaking these tests shouldn't need to interact with those actual classes so the correct course of action is probably to mock these objects out.

# Acceptance Criteria

Each test file can be run independently and all tests pass.

# Not Required

# Prerequisites

# Related Issues

# Due Date

# Design?

# Text?

# Bloggable?

**Comment by tmtmtmtm** [comment]
> $ bundle exec ruby -w -I"lib:t" "t/page/country.rb"

@henare Just checking you know that you can run a single test file using `bundle exec rake test TEST=t/page/country.rb`

**Comment by henare** [comment]
@tmtmtmtm I didn't - thanks for the very handy tip! 💚
