### ISSUE TITLE
Get test suite running on Travis CI

### ISSUE THREAD

**Issue by henare** [everypolitician/legislative-explorer#3]
# Problem

The test suite is not currently running on Travis: https://travis-ci.org/everypolitician/legislative-explorer/builds/336382785

There's a few reasons for this that we currently know about:

- [x] `tidy` install script [isn't working](https://travis-ci.org/everypolitician/legislative-explorer/builds/336382785#L883) - ☑️ [PR raised](https://github.com/everypolitician/legislative-explorer/pull/2)
- [x] Rubocop is detecting multiple offences - ☑️ [PR raised](https://github.com/everypolitician/legislative-explorer/pull/4)
- [x] Static site still being built (this probably won't cause a problem with PR builds but it will when the build script tries to deploy the site over the top of the viewer-static repo) - ☑️ [PR raised](https://github.com/everypolitician/legislative-explorer/pull/6)
- [ ] Test suite is out of sync with the codebase (the codebase was significantly refactored, e.g. https://github.com/everypolitician/legislative-explorer/commit/ea813503fff41c13a998b614f6d0d86194fb74d3 but the test suite wasn't updated to match)

# Proposed Solution

I think I'll split this up into separate PRs. The first few won't have a passing test suite but I hope we can consider that OK because it's not a regression.

Getting the test suite back in sync with the codebase is going to be a bit of work. As much as possible I'll try to replicate what the old tests were doing but with the new code structure. Hopefully that makes the reviews a bit easier and discourages us from refactoring the tests too much along the way.

# Acceptance Criteria

🍏 builds from Travis.

# Not Required

# Prerequisites

# Related Issues

# Due Date

# Design?

# Text?

# Bloggable?

**Comment by tmtmtmtm** [comment]
Travis is now green, so closing this one. We can open separate tickets for any further improvements. Thanks for your work on this @henare and sorry again for leaving everything in pieces on the floor in the first place!

**Comment by henare** [comment]
Superb, thanks @tmtmtmtm 🌟
